/*! dicomAnon - v0.3 */

var anon = {
    empty: 'empty',
    remove: 'remove',
    fixed: 'fixed',
    unique: 'unique',
    UI: 'UI'
};

var VR = {
    SQ: 'SQ',
    UI: 'UI'
};

var CHARS = {
    SPACE: 32,
    '*': 42
};

//How to build new tagCode: 
//Group , Element -> 0x0002 , 0x0001
//tagCode -> x00020001

//tags sobre los que se aplicará la anonimización
var tagsInfo = [
    //GENERAL
    {tagCode: 'x00020012', tagName: 'Implementation Class UID', anonMethod: anon.fixed, fixedVal: '****'},
    {tagCode: 'x00020013', tagName: 'Implementation Class UID', anonMethod: anon.fixed, fixedVal: 'ANON'},
    {tagCode: 'x00020016', tagName: 'Source Application Entity Title', anonMethod: anon.fixed, fixedVal: 'MFAR'},
    {tagCode: 'x00020100', tagName: 'Private Information Creator UID', anonMethod: anon.empty},
    {tagCode: 'x00020102', tagName: 'Private Information', anonMethod: anon.empty},
    //UID
    {tagCode: 'x00020003', tagName: 'Media Storage SOP Instance UID', anonMethod: anon.unique},
    //PATIENT
    {tagCode: 'x00100010', tagName: 'Patient s Name', anonMethod: anon.fixed, fixedVal: 'Anonymized^^'},
    {tagCode: 'x00100020', tagName: 'Patient ID', anonMethod: anon.fixed, fixedVal: '0'},
    {tagCode: 'x00100021', tagName: 'Issuer of Patient ID', anonMethod: anon.empty},
    {tagCode: 'x00100022', tagName: 'Type of Patient ID', anonMethod: anon.empty},
    {tagCode: 'x00100030', tagName: 'Patient s Birth Date', anonMethod: anon.empty},
    {tagCode: 'x00100032', tagName: 'Patient s Birth Time', anonMethod: anon.empty},
    {tagCode: 'x00100050', tagName: 'Patient s Insurance Plan Code Sequence', anonMethod: anon.remove},
    {tagCode: 'x00100101', tagName: 'Patient s Primary Language Code Sequence', anonMethod: anon.remove},
    {tagCode: 'x00100102', tagName: 'Patient s Primary Language Code Modifier Sequence', anonMethod: anon.remove},
    {tagCode: 'x00101000', tagName: 'Other Patient IDs', anonMethod: anon.empty},
    {tagCode: 'x00101001', tagName: 'Other Patient Names', anonMethod: anon.empty},
    {tagCode: 'x00101002', tagName: 'Other Patient IDs Sequence', anonMethod: anon.remove},
    {tagCode: 'x00101005', tagName: 'Patient s Birth Name', anonMethod: anon.empty},
    {tagCode: 'x00101040', tagName: 'Patient s Address', anonMethod: anon.empty},
    {tagCode: 'x00101050', tagName: 'Insurance Plan Identification (RET)', anonMethod: anon.empty},
    {tagCode: 'x00101060', tagName: 'Patients Mother s Birth Name', anonMethod: anon.empty},
    {tagCode: 'x00101080', tagName: 'Military Rank', anonMethod: anon.empty},
    {tagCode: 'x00101081', tagName: 'Branch of Service', anonMethod: anon.empty},
    {tagCode: 'x00101090', tagName: 'Medical Record Locator', anonMethod: anon.empty},
    {tagCode: 'x00102150', tagName: 'Country of Residence', anonMethod: anon.empty},
    {tagCode: 'x00102152', tagName: 'Region of Residence', anonMethod: anon.empty},
    {tagCode: 'x00102154', tagName: 'Patient s Telephone Numbers', anonMethod: anon.empty},
    {tagCode: 'x00102160', tagName: 'Ethnic Group', anonMethod: anon.empty},
    {tagCode: 'x00102180', tagName: 'Occupation', anonMethod: anon.empty},
    {tagCode: 'x001021b0', tagName: 'Additional Patient History', anonMethod: anon.empty},
    {tagCode: 'x001021c0', tagName: 'Pregnancy Status', anonMethod: anon.empty},
    {tagCode: 'x001021d0', tagName: 'Last Menstrual Date', anonMethod: anon.empty},
    {tagCode: 'x001021f0', tagName: 'Patient s Religious Preference', anonMethod: anon.remove},
    {tagCode: 'x00102202', tagName: 'Patient Species Code Sequence', anonMethod: anon.remove},
    {tagCode: 'x00102203', tagName: 'Patient s Sex Neutered', anonMethod: anon.empty},
    {tagCode: 'x00102293', tagName: 'Patient Breed Code Sequence', anonMethod: anon.remove},
    {tagCode: 'x00102294', tagName: 'Breed Registration Sequence', anonMethod: anon.remove},
    {tagCode: 'x00102295', tagName: 'Breed Registration Number', anonMethod: anon.empty},
    {tagCode: 'x00102296', tagName: 'Breed Registry Code Sequence', anonMethod: anon.remove},
    {tagCode: 'x00102297', tagName: 'Responsible Person', anonMethod: anon.empty},
    {tagCode: 'x00102298', tagName: 'Responsible Person Role', anonMethod: anon.empty},
    {tagCode: 'x00102299', tagName: 'Responsible Organization', anonMethod: anon.empty},
    //VISIT
    {tagCode: 'x00080080', tagName: 'Institution Name', anonMethod: anon.empty},
    {tagCode: 'x00080081', tagName: 'Institution Address', anonMethod: anon.empty},
    {tagCode: 'x00080082', tagName: 'Institution Code Sequence', anonMethod: anon.remove},
    {tagCode: 'x00080090', tagName: 'Referring Physician s Name', anonMethod: anon.empty},
    {tagCode: 'x00080092', tagName: 'Referring Physician s Address', anonMethod: anon.empty},
    {tagCode: 'x00080094', tagName: 'Referring Physician s Telephone Numbers', anonMethod: anon.empty},
    {tagCode: 'x00080096', tagName: 'Referring Physician Identification Sequence', anonMethod: anon.remove},
    {tagCode: 'x00080116', tagName: 'Responsible Organization', anonMethod: anon.empty},
    {tagCode: 'x00081048', tagName: 'Physician(s) of Record', anonMethod: anon.empty},
    {tagCode: 'x00081049', tagName: 'Physician(s) of Record Identification Sequence', anonMethod: anon.remove},
    {tagCode: 'x00081050', tagName: 'Performing Physician s Name', anonMethod: anon.empty},
    {tagCode: 'x00081052', tagName: 'Performing Physician Identification Sequence', anonMethod: anon.remove},
    {tagCode: 'x00081060', tagName: 'Name of Physician(s) Reading Study', anonMethod: anon.empty},
    {tagCode: 'x00081062', tagName: 'Physician(s) Reading Study Identification Sequence', anonMethod: anon.remove},
    {tagCode: 'x00081070', tagName: 'Operators Name', anonMethod: anon.empty},
    {tagCode: 'x00081072', tagName: 'Operator Identification Sequence', anonMethod: anon.remove},
    {tagCode: 'x00380010', tagName: 'Admission ID', anonMethod: anon.empty},
    {tagCode: 'x00380011', tagName: 'Issuer of Admission ID', anonMethod: anon.empty},
    {tagCode: 'x00380016', tagName: 'Route of Admissions', anonMethod: anon.empty},
    {tagCode: 'x0038001a', tagName: 'Scheduled Admission Date (RET)', anonMethod: anon.empty},
    {tagCode: 'x0038001b', tagName: 'Scheduled Admission Time (RET)', anonMethod: anon.empty},
    {tagCode: 'x0038001c', tagName: 'Scheduled Discharge Date (RET)', anonMethod: anon.empty},
    {tagCode: 'x0038001d', tagName: 'Scheduled Discharge Time (RET)', anonMethod: anon.empty},
    {tagCode: 'x0038001e', tagName: 'Scheduled Patient Institution Residence (RET)', anonMethod: anon.empty},
    {tagCode: 'x00380020', tagName: 'Admitting Date', anonMethod: anon.empty},
    {tagCode: 'x00380021', tagName: 'Admitting Time', anonMethod: anon.empty},
    {tagCode: 'x00380030', tagName: 'Discharge Date (RET)', anonMethod: anon.empty},
    {tagCode: 'x00380032', tagName: 'Discharge Time (RET)', anonMethod: anon.empty},
    {tagCode: 'x00380040', tagName: 'Discharge Diagnosis Description (RET)', anonMethod: anon.empty},
    {tagCode: 'x00380044', tagName: 'Discharge Diagnosis Code Sequence (RET)', anonMethod: anon.remove},
    {tagCode: 'x00380300', tagName: 'Current Patient Location', anonMethod: anon.empty},
    {tagCode: 'x00380400', tagName: 'Patient s Institution Residence', anonMethod: anon.empty},
    {tagCode: 'x00380500', tagName: 'Patient State', anonMethod: anon.empty},
    //STUDY
    {tagCode: 'x00200010', tagName: 'Study ID', anonMethod: anon.fixed, fixedVal: '1'},
    {tagCode: 'x00080050', tagName: 'Accession Number', anonMethod: anon.empty},
    {tagCode: 'x0032000a', tagName: 'Study Status ID (RET)', anonMethod: anon.empty},
    {tagCode: 'x0032000c', tagName: 'Study Priority ID (RET)', anonMethod: anon.empty},
    {tagCode: 'x00320012', tagName: 'Study ID Issuer (RET)', anonMethod: anon.empty},
    {tagCode: 'x00320032', tagName: 'Study Verified Date (RET)', anonMethod: anon.empty},
    {tagCode: 'x00320033', tagName: 'Study Verified Time (RET)', anonMethod: anon.empty},
    {tagCode: 'x00320034', tagName: 'Study Read Date (RET)', anonMethod: anon.empty},
    {tagCode: 'x00320035', tagName: 'Study Read Time (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321000', tagName: 'Scheduled Study Start Date (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321001', tagName: 'Scheduled Study Start Time (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321010', tagName: 'Scheduled Study Stop Date (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321011', tagName: 'Scheduled Study Stop Time (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321020', tagName: 'Scheduled Study Location (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321021', tagName: 'Scheduled Study Location AE Title (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321030', tagName: 'Reason for Study (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321031', tagName: 'Requesting Physician Identification Sequence', anonMethod: anon.remove},
    {tagCode: 'x00321032', tagName: 'Requesting Physician', anonMethod: anon.empty},
    {tagCode: 'x00321033', tagName: 'Requesting Service', anonMethod: anon.empty},
    {tagCode: 'x00321040', tagName: 'Study Arrival Date (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321041', tagName: 'Study Arrival Time (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321050', tagName: 'Study Completion Date (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321051', tagName: 'Study Completion Time (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321055', tagName: 'Study Component Status ID (RET)', anonMethod: anon.empty},
    {tagCode: 'x00321060', tagName: 'Requested Procedure Description', anonMethod: anon.empty},
    {tagCode: 'x00321064', tagName: 'Requested Procedure Code Sequence', anonMethod: anon.unique}, //provoca error en lectura del fichero
    {tagCode: 'x00321070', tagName: 'Requested Contrast Agent', anonMethod: anon.empty},
    {tagCode: 'x00324000', tagName: 'Study Comments', anonMethod: anon.empty},
    {tagCode: 'x00402008', tagName: 'Order Entered By', anonMethod: anon.empty},
    {tagCode: 'x00402009', tagName: 'Order Enterer s Location', anonMethod: anon.empty},
    {tagCode: 'x00402010', tagName: 'Order Callback Phone Number', anonMethod: anon.empty},
    //PROCEDURE
    {tagCode: 'x00400001', tagName: 'Scheduled Station AE Title', anonMethod: anon.empty},
    {tagCode: 'x00400006', tagName: 'Scheduled Performing Physician s Name', anonMethod: anon.empty},
    {tagCode: 'x0040000b', tagName: 'Scheduled Performing Physician Identification Sequence', anonMethod: anon.remove},
    {tagCode: 'x00400010', tagName: 'Scheduled Station Name', anonMethod: anon.empty},
    {tagCode: 'x00400011', tagName: 'Scheduled Procedure Step Location'},
    {tagCode: 'x00400012', tagName: 'Pre-Medication', anonMethod: anon.empty},
    {tagCode: 'x00400241', tagName: 'Performed Station AE Title', anonMethod: anon.empty},
    {tagCode: 'x00400242', tagName: 'Performed Station Name', anonMethod: anon.empty},
    {tagCode: 'x00400243', tagName: 'Performed Location', anonMethod: anon.empty},
    {tagCode: 'x00400296', tagName: 'Billing Item Sequence', anonMethod: anon.remove},
    //RESULT
    {tagCode: 'x40080042', tagName: 'Results ID Issuer (RET)', anonMethod: anon.empty},
    //INTERPRETATION
    {tagCode: 'x4008010c', tagName: 'Interpretation Author (RET)', anonMethod: anon.empty},
    {tagCode: 'x40080114', tagName: 'Physician Approving Interpretation (RET)', anonMethod: anon.empty},
    {tagCode: 'x40080119', tagName: 'Distribution Name (RET)', anonMethod: anon.empty},
    {tagCode: 'x4008011a', tagName: 'Distribution Address (RET)', anonMethod: anon.empty},
    {tagCode: 'x40080202', tagName: 'Interpretation ID Issuer (RET)', anonMethod: anon.empty},
    //EQUIPMENT
    {tagCode: 'x00080070', tagName: 'Manufacturer', anonMethod: anon.empty},
    {tagCode: 'x00081010', tagName: 'Station Name', anonMethod: anon.empty},
    {tagCode: 'x00081040', tagName: 'Institutional Department Name', anonMethod: anon.empty},
    {tagCode: 'x00081090', tagName: 'Manufacturer\'s Model Name', anonMethod: anon.empty},
    {tagCode: 'x00181000', tagName: 'Device Serial Number', anonMethod: anon.empty},
    {tagCode: 'x00181016', tagName: 'Secondary Capture Device Manufacturer', anonMethod: anon.empty},
    {tagCode: 'x00181017', tagName: 'Hardcopy Device Manufacturer', anonMethod: anon.empty},
    {tagCode: 'x00181018', tagName: 'Secondary Capture Device Manufacturer\'s Model Name', anonMethod: anon.empty},
    {tagCode: 'x00181019', tagName: 'Secondary Capture Device Software Version(s)', anonMethod: anon.empty},
    {tagCode: 'x0018101a', tagName: 'Hardcopy Device Software Version', anonMethod: anon.empty},
    {tagCode: 'x0018101b', tagName: 'Hardcopy Device Manufacturer\'s Model Name', anonMethod: anon.empty},
    {tagCode: 'x00181020', tagName: 'Software Version(s)', anonMethod: anon.empty},
    {tagCode: 'x00181200', tagName: 'Date of Last Calibration', anonMethod: anon.empty},
    {tagCode: 'x00181201', tagName: 'Time of Last Calibration', anonMethod: anon.empty},
    {tagCode: 'x0018700c', tagName: 'Date of Last Detector Calibration', anonMethod: anon.empty},
    {tagCode: 'x0018700e', tagName: 'Time of Last Detector Calibration', anonMethod: anon.empty},
    {tagCode: 'x00187010', tagName: 'Exposures on Detector Since Last Calibration', anonMethod: anon.empty},
    {tagCode: 'x00187011', tagName: 'Exposures on Detector Since Manufactured', anonMethod: anon.empty},
    //TEST
    // {tagCode: 'x00400275', 'tagName': 'RequestAttributesSequence', anonMethod: anon.unique} //ejemplo a 3 niveles
];